/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as FavoritterRouteImport } from './routes/favoritter'
import { Route as NavneforslagRouteImport } from './routes/navneforslag'
import { Route as NavnestatistikkRouteImport } from './routes/navnestatistikk'
import { Route as PopulaereNavnRouteImport } from './routes/populaere-navn'
import { Route as SokRouteImport } from './routes/sok'
import { Route as GuttenavnIndexRouteImport } from './routes/guttenavn.index'
import { Route as HundenavnIndexRouteImport } from './routes/hundenavn.index'
import { Route as JentenavnIndexRouteImport } from './routes/jentenavn.index'
import { Route as KattenavnIndexRouteImport } from './routes/kattenavn.index'
import { Route as NavnSlugRouteImport } from './routes/navn.$slug'
import { Route as GuttenavnBokstavLetterRouteImport } from './routes/guttenavn.bokstav.$letter'
import { Route as GuttenavnKategoriStyleRouteImport } from './routes/guttenavn.kategori.$style'
import { Route as GuttenavnLengdeLengthRouteImport } from './routes/guttenavn.lengde.$length'
import { Route as HundenavnBokstavLetterRouteImport } from './routes/hundenavn.bokstav.$letter'
import { Route as HundenavnLengdeLengthRouteImport } from './routes/hundenavn.lengde.$length'
import { Route as JentenavnBokstavLetterRouteImport } from './routes/jentenavn.bokstav.$letter'
import { Route as JentenavnKategoriStyleRouteImport } from './routes/jentenavn.kategori.$style'
import { Route as JentenavnLengdeLengthRouteImport } from './routes/jentenavn.lengde.$length'
import { Route as KattenavnBokstavLetterRouteImport } from './routes/kattenavn.bokstav.$letter'
import { Route as KattenavnLengdeLengthRouteImport } from './routes/kattenavn.lengde.$length'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritterRoute = FavoritterRouteImport.update({
  id: '/favoritter',
  path: '/favoritter',
  getParentRoute: () => rootRouteImport,
} as any)
const NavneforslagRoute = NavneforslagRouteImport.update({
  id: '/navneforslag',
  path: '/navneforslag',
  getParentRoute: () => rootRouteImport,
} as any)
const NavnestatistikkRoute = NavnestatistikkRouteImport.update({
  id: '/navnestatistikk',
  path: '/navnestatistikk',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulaereNavnRoute = PopulaereNavnRouteImport.update({
  id: '/populaere-navn',
  path: '/populaere-navn',
  getParentRoute: () => rootRouteImport,
} as any)
const SokRoute = SokRouteImport.update({
  id: '/sok',
  path: '/sok',
  getParentRoute: () => rootRouteImport,
} as any)
const GuttenavnIndexRoute = GuttenavnIndexRouteImport.update({
  id: '/guttenavn/',
  path: '/guttenavn/',
  getParentRoute: () => rootRouteImport,
} as any)
const HundenavnIndexRoute = HundenavnIndexRouteImport.update({
  id: '/hundenavn/',
  path: '/hundenavn/',
  getParentRoute: () => rootRouteImport,
} as any)
const JentenavnIndexRoute = JentenavnIndexRouteImport.update({
  id: '/jentenavn/',
  path: '/jentenavn/',
  getParentRoute: () => rootRouteImport,
} as any)
const KattenavnIndexRoute = KattenavnIndexRouteImport.update({
  id: '/kattenavn/',
  path: '/kattenavn/',
  getParentRoute: () => rootRouteImport,
} as any)
const NavnSlugRoute = NavnSlugRouteImport.update({
  id: '/navn/$slug',
  path: '/navn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuttenavnBokstavLetterRoute = GuttenavnBokstavLetterRouteImport.update({
  id: '/guttenavn/bokstav/$letter',
  path: '/guttenavn/bokstav/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const GuttenavnKategoriStyleRoute = GuttenavnKategoriStyleRouteImport.update({
  id: '/guttenavn/kategori/$style',
  path: '/guttenavn/kategori/$style',
  getParentRoute: () => rootRouteImport,
} as any)
const GuttenavnLengdeLengthRoute = GuttenavnLengdeLengthRouteImport.update({
  id: '/guttenavn/lengde/$length',
  path: '/guttenavn/lengde/$length',
  getParentRoute: () => rootRouteImport,
} as any)
const HundenavnBokstavLetterRoute = HundenavnBokstavLetterRouteImport.update({
  id: '/hundenavn/bokstav/$letter',
  path: '/hundenavn/bokstav/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const HundenavnLengdeLengthRoute = HundenavnLengdeLengthRouteImport.update({
  id: '/hundenavn/lengde/$length',
  path: '/hundenavn/lengde/$length',
  getParentRoute: () => rootRouteImport,
} as any)
const JentenavnBokstavLetterRoute = JentenavnBokstavLetterRouteImport.update({
  id: '/jentenavn/bokstav/$letter',
  path: '/jentenavn/bokstav/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const JentenavnKategoriStyleRoute = JentenavnKategoriStyleRouteImport.update({
  id: '/jentenavn/kategori/$style',
  path: '/jentenavn/kategori/$style',
  getParentRoute: () => rootRouteImport,
} as any)
const JentenavnLengdeLengthRoute = JentenavnLengdeLengthRouteImport.update({
  id: '/jentenavn/lengde/$length',
  path: '/jentenavn/lengde/$length',
  getParentRoute: () => rootRouteImport,
} as any)
const KattenavnBokstavLetterRoute = KattenavnBokstavLetterRouteImport.update({
  id: '/kattenavn/bokstav/$letter',
  path: '/kattenavn/bokstav/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const KattenavnLengdeLengthRoute = KattenavnLengdeLengthRouteImport.update({
  id: '/kattenavn/lengde/$length',
  path: '/kattenavn/lengde/$length',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/favoritter': typeof FavoritterRoute
  '/navneforslag': typeof NavneforslagRoute
  '/navnestatistikk': typeof NavnestatistikkRoute
  '/populaere-navn': typeof PopulaereNavnRoute
  '/sok': typeof SokRoute
  '/navn/$slug': typeof NavnSlugRoute
  '/guttenavn/': typeof GuttenavnIndexRoute
  '/hundenavn/': typeof HundenavnIndexRoute
  '/jentenavn/': typeof JentenavnIndexRoute
  '/kattenavn/': typeof KattenavnIndexRoute
  '/guttenavn/bokstav/$letter': typeof GuttenavnBokstavLetterRoute
  '/guttenavn/kategori/$style': typeof GuttenavnKategoriStyleRoute
  '/guttenavn/lengde/$length': typeof GuttenavnLengdeLengthRoute
  '/hundenavn/bokstav/$letter': typeof HundenavnBokstavLetterRoute
  '/hundenavn/lengde/$length': typeof HundenavnLengdeLengthRoute
  '/jentenavn/bokstav/$letter': typeof JentenavnBokstavLetterRoute
  '/jentenavn/kategori/$style': typeof JentenavnKategoriStyleRoute
  '/jentenavn/lengde/$length': typeof JentenavnLengdeLengthRoute
  '/kattenavn/bokstav/$letter': typeof KattenavnBokstavLetterRoute
  '/kattenavn/lengde/$length': typeof KattenavnLengdeLengthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/favoritter': typeof FavoritterRoute
  '/navneforslag': typeof NavneforslagRoute
  '/navnestatistikk': typeof NavnestatistikkRoute
  '/populaere-navn': typeof PopulaereNavnRoute
  '/sok': typeof SokRoute
  '/navn/$slug': typeof NavnSlugRoute
  '/guttenavn': typeof GuttenavnIndexRoute
  '/hundenavn': typeof HundenavnIndexRoute
  '/jentenavn': typeof JentenavnIndexRoute
  '/kattenavn': typeof KattenavnIndexRoute
  '/guttenavn/bokstav/$letter': typeof GuttenavnBokstavLetterRoute
  '/guttenavn/kategori/$style': typeof GuttenavnKategoriStyleRoute
  '/guttenavn/lengde/$length': typeof GuttenavnLengdeLengthRoute
  '/hundenavn/bokstav/$letter': typeof HundenavnBokstavLetterRoute
  '/hundenavn/lengde/$length': typeof HundenavnLengdeLengthRoute
  '/jentenavn/bokstav/$letter': typeof JentenavnBokstavLetterRoute
  '/jentenavn/kategori/$style': typeof JentenavnKategoriStyleRoute
  '/jentenavn/lengde/$length': typeof JentenavnLengdeLengthRoute
  '/kattenavn/bokstav/$letter': typeof KattenavnBokstavLetterRoute
  '/kattenavn/lengde/$length': typeof KattenavnLengdeLengthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/favoritter': typeof FavoritterRoute
  '/navneforslag': typeof NavneforslagRoute
  '/navnestatistikk': typeof NavnestatistikkRoute
  '/populaere-navn': typeof PopulaereNavnRoute
  '/sok': typeof SokRoute
  '/navn/$slug': typeof NavnSlugRoute
  '/guttenavn/': typeof GuttenavnIndexRoute
  '/hundenavn/': typeof HundenavnIndexRoute
  '/jentenavn/': typeof JentenavnIndexRoute
  '/kattenavn/': typeof KattenavnIndexRoute
  '/guttenavn/bokstav/$letter': typeof GuttenavnBokstavLetterRoute
  '/guttenavn/kategori/$style': typeof GuttenavnKategoriStyleRoute
  '/guttenavn/lengde/$length': typeof GuttenavnLengdeLengthRoute
  '/hundenavn/bokstav/$letter': typeof HundenavnBokstavLetterRoute
  '/hundenavn/lengde/$length': typeof HundenavnLengdeLengthRoute
  '/jentenavn/bokstav/$letter': typeof JentenavnBokstavLetterRoute
  '/jentenavn/kategori/$style': typeof JentenavnKategoriStyleRoute
  '/jentenavn/lengde/$length': typeof JentenavnLengdeLengthRoute
  '/kattenavn/bokstav/$letter': typeof KattenavnBokstavLetterRoute
  '/kattenavn/lengde/$length': typeof KattenavnLengdeLengthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/favoritter'
    | '/navneforslag'
    | '/navnestatistikk'
    | '/populaere-navn'
    | '/sok'
    | '/navn/$slug'
    | '/guttenavn/'
    | '/hundenavn/'
    | '/jentenavn/'
    | '/kattenavn/'
    | '/guttenavn/bokstav/$letter'
    | '/guttenavn/kategori/$style'
    | '/guttenavn/lengde/$length'
    | '/hundenavn/bokstav/$letter'
    | '/hundenavn/lengde/$length'
    | '/jentenavn/bokstav/$letter'
    | '/jentenavn/kategori/$style'
    | '/jentenavn/lengde/$length'
    | '/kattenavn/bokstav/$letter'
    | '/kattenavn/lengde/$length'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/favoritter'
    | '/navneforslag'
    | '/navnestatistikk'
    | '/populaere-navn'
    | '/sok'
    | '/navn/$slug'
    | '/guttenavn'
    | '/hundenavn'
    | '/jentenavn'
    | '/kattenavn'
    | '/guttenavn/bokstav/$letter'
    | '/guttenavn/kategori/$style'
    | '/guttenavn/lengde/$length'
    | '/hundenavn/bokstav/$letter'
    | '/hundenavn/lengde/$length'
    | '/jentenavn/bokstav/$letter'
    | '/jentenavn/kategori/$style'
    | '/jentenavn/lengde/$length'
    | '/kattenavn/bokstav/$letter'
    | '/kattenavn/lengde/$length'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/favoritter'
    | '/navneforslag'
    | '/navnestatistikk'
    | '/populaere-navn'
    | '/sok'
    | '/navn/$slug'
    | '/guttenavn/'
    | '/hundenavn/'
    | '/jentenavn/'
    | '/kattenavn/'
    | '/guttenavn/bokstav/$letter'
    | '/guttenavn/kategori/$style'
    | '/guttenavn/lengde/$length'
    | '/hundenavn/bokstav/$letter'
    | '/hundenavn/lengde/$length'
    | '/jentenavn/bokstav/$letter'
    | '/jentenavn/kategori/$style'
    | '/jentenavn/lengde/$length'
    | '/kattenavn/bokstav/$letter'
    | '/kattenavn/lengde/$length'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  FavoritterRoute: typeof FavoritterRoute
  NavneforslagRoute: typeof NavneforslagRoute
  NavnestatistikkRoute: typeof NavnestatistikkRoute
  PopulaereNavnRoute: typeof PopulaereNavnRoute
  SokRoute: typeof SokRoute
  NavnSlugRoute: typeof NavnSlugRoute
  GuttenavnIndexRoute: typeof GuttenavnIndexRoute
  HundenavnIndexRoute: typeof HundenavnIndexRoute
  JentenavnIndexRoute: typeof JentenavnIndexRoute
  KattenavnIndexRoute: typeof KattenavnIndexRoute
  GuttenavnBokstavLetterRoute: typeof GuttenavnBokstavLetterRoute
  GuttenavnKategoriStyleRoute: typeof GuttenavnKategoriStyleRoute
  GuttenavnLengdeLengthRoute: typeof GuttenavnLengdeLengthRoute
  HundenavnBokstavLetterRoute: typeof HundenavnBokstavLetterRoute
  HundenavnLengdeLengthRoute: typeof HundenavnLengdeLengthRoute
  JentenavnBokstavLetterRoute: typeof JentenavnBokstavLetterRoute
  JentenavnKategoriStyleRoute: typeof JentenavnKategoriStyleRoute
  JentenavnLengdeLengthRoute: typeof JentenavnLengdeLengthRoute
  KattenavnBokstavLetterRoute: typeof KattenavnBokstavLetterRoute
  KattenavnLengdeLengthRoute: typeof KattenavnLengdeLengthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritter': {
      id: '/favoritter'
      path: '/favoritter'
      fullPath: '/favoritter'
      preLoaderRoute: typeof FavoritterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navneforslag': {
      id: '/navneforslag'
      path: '/navneforslag'
      fullPath: '/navneforslag'
      preLoaderRoute: typeof NavneforslagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navnestatistikk': {
      id: '/navnestatistikk'
      path: '/navnestatistikk'
      fullPath: '/navnestatistikk'
      preLoaderRoute: typeof NavnestatistikkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/populaere-navn': {
      id: '/populaere-navn'
      path: '/populaere-navn'
      fullPath: '/populaere-navn'
      preLoaderRoute: typeof PopulaereNavnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sok': {
      id: '/sok'
      path: '/sok'
      fullPath: '/sok'
      preLoaderRoute: typeof SokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guttenavn/': {
      id: '/guttenavn/'
      path: '/guttenavn'
      fullPath: '/guttenavn/'
      preLoaderRoute: typeof GuttenavnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hundenavn/': {
      id: '/hundenavn/'
      path: '/hundenavn'
      fullPath: '/hundenavn/'
      preLoaderRoute: typeof HundenavnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jentenavn/': {
      id: '/jentenavn/'
      path: '/jentenavn'
      fullPath: '/jentenavn/'
      preLoaderRoute: typeof JentenavnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kattenavn/': {
      id: '/kattenavn/'
      path: '/kattenavn'
      fullPath: '/kattenavn/'
      preLoaderRoute: typeof KattenavnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navn/$slug': {
      id: '/navn/$slug'
      path: '/navn/$slug'
      fullPath: '/navn/$slug'
      preLoaderRoute: typeof NavnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guttenavn/bokstav/$letter': {
      id: '/guttenavn/bokstav/$letter'
      path: '/guttenavn/bokstav/$letter'
      fullPath: '/guttenavn/bokstav/$letter'
      preLoaderRoute: typeof GuttenavnBokstavLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guttenavn/kategori/$style': {
      id: '/guttenavn/kategori/$style'
      path: '/guttenavn/kategori/$style'
      fullPath: '/guttenavn/kategori/$style'
      preLoaderRoute: typeof GuttenavnKategoriStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guttenavn/lengde/$length': {
      id: '/guttenavn/lengde/$length'
      path: '/guttenavn/lengde/$length'
      fullPath: '/guttenavn/lengde/$length'
      preLoaderRoute: typeof GuttenavnLengdeLengthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hundenavn/bokstav/$letter': {
      id: '/hundenavn/bokstav/$letter'
      path: '/hundenavn/bokstav/$letter'
      fullPath: '/hundenavn/bokstav/$letter'
      preLoaderRoute: typeof HundenavnBokstavLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hundenavn/lengde/$length': {
      id: '/hundenavn/lengde/$length'
      path: '/hundenavn/lengde/$length'
      fullPath: '/hundenavn/lengde/$length'
      preLoaderRoute: typeof HundenavnLengdeLengthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jentenavn/bokstav/$letter': {
      id: '/jentenavn/bokstav/$letter'
      path: '/jentenavn/bokstav/$letter'
      fullPath: '/jentenavn/bokstav/$letter'
      preLoaderRoute: typeof JentenavnBokstavLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jentenavn/kategori/$style': {
      id: '/jentenavn/kategori/$style'
      path: '/jentenavn/kategori/$style'
      fullPath: '/jentenavn/kategori/$style'
      preLoaderRoute: typeof JentenavnKategoriStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jentenavn/lengde/$length': {
      id: '/jentenavn/lengde/$length'
      path: '/jentenavn/lengde/$length'
      fullPath: '/jentenavn/lengde/$length'
      preLoaderRoute: typeof JentenavnLengdeLengthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kattenavn/bokstav/$letter': {
      id: '/kattenavn/bokstav/$letter'
      path: '/kattenavn/bokstav/$letter'
      fullPath: '/kattenavn/bokstav/$letter'
      preLoaderRoute: typeof KattenavnBokstavLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kattenavn/lengde/$length': {
      id: '/kattenavn/lengde/$length'
      path: '/kattenavn/lengde/$length'
      fullPath: '/kattenavn/lengde/$length'
      preLoaderRoute: typeof KattenavnLengdeLengthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  FavoritterRoute: FavoritterRoute,
  NavneforslagRoute: NavneforslagRoute,
  NavnestatistikkRoute: NavnestatistikkRoute,
  PopulaereNavnRoute: PopulaereNavnRoute,
  SokRoute: SokRoute,
  NavnSlugRoute: NavnSlugRoute,
  GuttenavnIndexRoute: GuttenavnIndexRoute,
  HundenavnIndexRoute: HundenavnIndexRoute,
  JentenavnIndexRoute: JentenavnIndexRoute,
  KattenavnIndexRoute: KattenavnIndexRoute,
  GuttenavnBokstavLetterRoute: GuttenavnBokstavLetterRoute,
  GuttenavnKategoriStyleRoute: GuttenavnKategoriStyleRoute,
  GuttenavnLengdeLengthRoute: GuttenavnLengdeLengthRoute,
  HundenavnBokstavLetterRoute: HundenavnBokstavLetterRoute,
  HundenavnLengdeLengthRoute: HundenavnLengdeLengthRoute,
  JentenavnBokstavLetterRoute: JentenavnBokstavLetterRoute,
  JentenavnKategoriStyleRoute: JentenavnKategoriStyleRoute,
  JentenavnLengdeLengthRoute: JentenavnLengdeLengthRoute,
  KattenavnBokstavLetterRoute: KattenavnBokstavLetterRoute,
  KattenavnLengdeLengthRoute: KattenavnLengdeLengthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
